language: csharp

sudo: false  # use the new container-based Travis infrastructure
dist: bionic
dotnet: 3.1

before_script:
  - nvm install --lts
  - nvm use --lts
  - dotnet tool restore

cache:
  yarn: true
  directories:
    - '$HOME/.nuget/packages'

script:
  - fake build -t Build
